name: CI/CD
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
    - run: npm i --force
    - run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: root
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/cmbr.media
          git pull origin main
          git status
          npm i --force
          npm run build
          pm2 restart cmbr.media
